apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sqlserver
  name: sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      terminationGracePeriodSeconds: 30
      hostname: sqlserver
      securityContext:
        fsGroup: 10001
      containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-latest
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "@docker@2021"
            - name: MSSQL_AGENT_ENABLED
              value: "True"
          ports:
            - containerPort: 1433
          volumeMounts:
            - mountPath: /var/opt/mssql/data
              name: mssqldb
      volumes:
        - name: mssqldb
          emptyDir: {}
