apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: transactions-api
  name: transactions-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transactions-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: transactions-api
    spec:
      containers:
        - name: transactions-api
          image: jailtonjunior/transactions_api:v3
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
