version: "3"

services:
  api:
    container_name: api
    image: transaction-api
    build:
      context: .
      dockerfile: src/Transactions.API/Dockerfile
    restart: always
    ports:
      - "443:7204"
    depends_on:
      - mssql
      - mongodb
      - debezium_connect
      - worker
    networks:
      - transactions_net
    environment:
      ASPNETCORE_ENVIRONMENT: 'Development'

  worker:
    container_name: worker
    image: transaction-worker
    build:
      context: .
      dockerfile: src/Transactions.Worker/Dockerfile
    restart: always
    depends_on:
      - mssql
      - mongodb
      - debezium_connect
    networks:
      - transactions_net
    environment:
      DOTNET_ENVIRONMENT: 'Development'

  mssql:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - "1433:1433"
    networks:
      - transactions_net
    volumes:
      - ./.docker/data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: '@docker@2021'
      MSSQL_AGENT_ENABLED: 'True'

  mongodb:
    container_name: mongodb
    image: mongo:5.0.6
    restart: always
    volumes:
      - ./.docker/data:/data/db
    ports:
      - "27017:27017"
    networks:
      - transactions_net

  debezium_connect:
    container_name: debezium_connect
    image: debezium/connect:1.8
    restart: always
    depends_on:
      - mssql
    ports:
      - 8083:8083
    networks:
      - transactions_net
    environment:
      - BOOTSTRAP_SERVERS=transactions-events.servicebus.windows.net:9093
      - GROUP_ID=transaction_consumer_group
      - CONFIG_STORAGE_TOPIC=debezium_configs
      - OFFSET_STORAGE_TOPIC=debezium_offsets
      - STATUS_STORAGE_TOPIC=debezium_statuses
      - CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECT_OFFSET_STORAGE_PARTITIONS=1
      - CONNECT_STATUS_STORAGE_PARTITIONS=1
      - CONNECT_REQUEST_TIMEOUT_MS=60000
      - CONNECT_SECURITY_PROTOCOL=SASL_SSL
      - CONNECT_SASL_MECHANISM=PLAIN
      - CONNECT_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="{EH_CONNECTION}";
      - CONNECT_PRODUCER_SECURITY_PROTOCOL=SASL_SSL
      - CONNECT_PRODUCER_SASL_MECHANISM=PLAIN
      - CONNECT_PRODUCER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="{EH_CONNECTION}";
      - CONNECT_CONSUMER_SECURITY_PROTOCOL=SASL_SSL
      - CONNECT_CONSUMER_SASL_MECHANISM=PLAIN
      - CONNECT_CONSUMER_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="$$ConnectionString" password="{EH_CONNECTION}";

networks:
  transactions_net:
    driver: bridge
